### ISSUE TITLE
HtmlDocument, add constructor with parameter like html string

### ISSUE THREAD

**Issue by t-smirnov** [sy-github/HtmlAgilityPackLite#1]
Hello :)
This is the only one repo, that recently updated
Can you add constructor to class HtmlDocument with parameter that represents string of html code?
Or any static factory method, like:
`var document = new HtmlDocument("SomeHtmlString");
`
or
`var document = HtmlDocument.CreateFrom("SomeHtmlString");`

Thanks.

**Comment by sy-github** [comment]
@t-smirnov Yes, I will have a look.
